---
title: "When did Republicans quit thinking?"
publishDate: "2004-09-07"
tags: 
  - "politics"
---

If there is any consistent identifying feature of Republican doctrine prior to the advent of the Bush Dynasty, it is fiscal responsibility -- balancing the budget, knowing where the dollars are coming from, holding on to our credit-worthy status, being a good solid banker. George W. Bush is not a Republican in this sense. He just _talks about_ fiscal responsibility. Really he is leading his Republican Congress to give him the farm. (That would be the one they wouldn't have to sell to pay the inheritance tax. So much better to just give it to him up front.) The children of this country are mortgaged for the next three generations by the fiscal policies of the Bush administration. John at Thudfactor cites the [Bush fakery on the $87 billion for operations in Iraq:](http://www.thudfactor.com/textpattern/index.php?id=899)

> Bush threatened a veto of this bill. The version that passed had no legislation to indicate where that money would come from. Kerry?s vote against this bill was a vote for fiscal responsibility. Fiscal health is our number one weapon in any war. If we have no money and no one trusts our credit, how will we field an army? Kerry supported the bill when it was responsible, but Bush demanded a bill that was irresponsible.

John Kerry didn't "flip-flop." He just read the fine print and voted for responsible leadership. Apparently, "flip-flop" is Bush-speak for thinking about anything long enough to develop any insight. Bush worked his double-speak magic, which is pure and simple obfuscation, clouding the issue while he picked our pockets as Howard Gleckman explained in [BusinessWeek Online, September 10, 2003:](http://www.businessweek.com/print/bwdaily/dnflash/sep2003/nf20030910_2527_db045.htm?db)

> There's just one problem. While Bush and Congress are fighting over every dollar, they're going to pretend the $87 billion in Iraq money doesn't count as part of the discretionary budget ceiling, even though every thing else the Pentagon does is included. This is an accounting gimmick that would shame even Enron. "We will hold down spending," Bush and GOP leaders on Capitol Hill will say. But next to that boast will be a little imaginary asterisk that says, "For everything, that is, but Social Security, Medicare, Medicaid, a fistful of trust funds, and the war in Iraq." In truth, the government will spend more than $1.3 trillion next year -- close to twice the discretionary-spending target -- on stuff that doesn't count in Washington's debates over fiscal responsibility.

No bleeding heart liberal public assistance policy in the history of the world has been so blatantly dismissive of fiscal responsibility. When you compare the [cost of the Iraq war](http://costofwar.com/) to the cost of social programs, the magnitude of the deception and waste becomes apparent. Add to this cost the fact that the Iraq war has undone all of the good effects of negotiation and containment and empowered the recruitment of terrorists. This war has increased terrorism by increasing injustice, poverty, and fear, which are the root causes of terrorism. The world is not safer. Read a newspaper once a week. Who is still supporting George W. Bush? Are there that many people who cannot see that he is not a Republican any more than he is a Democrat? He is not a statesman at all. He demonstrates no sense of responsibility even for his own outcomes, much less the conservative Republican fiscal responsibility and committment to good management. He does not serve the universal values of peace and justice. If he gets one vote in November that vote will be have to be based upon ignorance.
