---
title: "The proposed tax compromise"
publishDate: "2010-12-08"
---

For those who are disappointed with the tax compromise, it is important to remember that people who voted for Republicans last month and Democrats who did not vote put President Obama in this position. He works with obstructionists because Americans voted for obstructionists whose only campaign promise was to "stop Obama."

The reason that the GOP can commit to obstruction and vote against ideas that were their own inventions -- the public option in health care and Cap and Trade are examples -- is that they have given up thinking about governing or what is best for the United States. They do not care if our nation drowns in the deficit and our people descend into poverty if they can achieve their own stated highest priority, which is to defeat President Obama in 2012.

In negotiating to extend the tax cuts for millionaires, Republicans attacked the child tax credit, the tuition tax credit, tax cuts for low-income and middle-income people, and the earned income tax credit -- all of which benefit working American families who struggle to make ends meet. They also threatened to block extension of unemployment benefits for millions of workers who lost jobs in the recession, people who would be without anything to live on, losing homes, and moving into poverty because the recovery hasn't reached them yet. All of these needs were placed in the balance against the desire of the GOP to preserve the tax cuts for the wealthy. Their message was clear that if the corporate interests that fund the GOP do not get their share first, nobody gets anything. By this means they forced the compromise proposal.

The compromise proposal buys time for further negotiation, and another two years of deficit-building. In 2012 Republicans will still be shouting about out-of-control spending and the runaway deficit and recommending cuts to Medicare, Social Security, education, and every other program that benefits the 98% of us who don't make $250,000.00 or more a year. The unfunded tax cuts for the wealthy are already around 40% of the deficit, and an unfunded extension will further weaken the U.S. economy internationally as well as here at home. If the tax cuts for the wealthy are extended and added once again to the deficit, we can only hope voters will remember this in 2012: Republicans made the unfunded tax cuts in the first place and ballooned the deficit, then held poor and middle-income families, children, students, and the unemployed hostage and disregarded another significant increase in the national deficit so that they could put money in their own pockets and those of their corporate sponsors.
