---
title: "Economists and politicians and greedy people"
publishDate: "2010-04-22"
tags: 
  - "taxing-and-spending"
---

From the Tea Party to the other extreme, which so far as I know has not been adequately named, the U.S. population seems to agree that finance reform is needed to stop greedy people in powerful financial institutions from creating fraudulent products to line their pockets and designing consumer credit to empty ours. Economists agree, people agree, and on most points even banks agree. Big banks made big money and got bailed out, while some smaller banks closed their doors; so they know there is a problem.

The debate will be an interesting because there is so much agreement. Politicians cannot be seen to have agreed with the wrong people, so we have the stand-off reported in _The New York Times_ today in an article by Wyatt and Herszenhorn titled ["Bill on Finance Wins Approval of Senate Panel:"](http://www.nytimes.com/2010/04/22/business/22regulate.html?th&emc=th)

> Republicans said that they had forced Democrats back to the bargaining table to negotiate a bipartisan accord, while Democrats said that Republicans were hastily abandoning their opposition in fear of a public outcry.

Another dimension in this debate is that the people who are actually interested -- it is economics, remember -- are more educated, better informed, and more critical. In the health care debate, Republicans tagged end-of-life counseling as "death panels," and they got a lot of street action from what was actually just a lie. In the financial reform debate, Democrats talked about having banks pay into a fund so that if they failed in the future this fund could be used to _finance their liquidation_. Republicans immediately tagged this fund a "bail-out fund," and Fox News announced that Democrats were not preventing future bailouts, but were in fact guaranteeing future bailouts. The story worked on the street for an hour or two, then someone noticed that it was a lie. Soon after the lie died, Democrats and Republicans and the public -- in what order we are not sure -- found out that President Obama didn't like the fund idea, so that left Republicans agreeing with President Obama. So everyone had to take a look at the likely effects of such a fund, and now practically nobody thinks it is a good idea, including me. I was with the Democrats at first, and I knew the Republicans were lying. But when I looked at the issue more closely, I now find that I agree with President Obama, the Republicans, and the Democrats on this particular aspect of financial reform.

What nobody can really tell is whether the Democrats proposed something and the Republicans drove them back to the bargaining table to start over, or the Democrats thought of something and reconsidered it with input from President Obama, or the Republicans abandoned their opposition because of fear of public outcry. We will never know. But among us there are some who will continue -- absent any knowledge, mind you -- to care deeply. That is probably because they got into a habit of calling the other side evil, sneaky, mean, lying Nazi-Fascist-Socialist idiots. So by habit they must think of something to put on a sign in no more than six words to show to each other to tell each other how bad everyone else is. But the topic is _economics_, and _practically everyone agrees on just about all of the points_. So the sign-carrying population has a lot of tried-and-true insulting adjectives and nouns, but they can't figure out which ones go with which. So we are likely to have a substantive discussion resulting in a strong piece of legislation, which will be, well, interesting.
